### PR TITLE
Update NFPropulsionISRU.cfg

### PR DESCRIPTION
**Pull request by TheToric**
first time using git, so i hope i did this right. replaces the mm cfg that adds a lithium refinery to the ISRUs. the old one only added the converters to the stock ones. this cfg looks for any converter that can convert ore into monoprop, and then adds an ore to lithium converter. keeps the same ratios, so the stock two will have the same stats as before, and scales it for third pary ISRUs based on their monoprop converters.

### CODE REVIEW

**Comment by Wyzard256** [comment]
Nils277's [Kerbal Planetary Base Systems](http://forum.kerbalspaceprogram.com/index.php?/topic/133606-121/) has an ISRU part that would benefit from this.  Currently, it doesn't get the lithium production added, nor the LH2 production from CryoTanks.

I made a patch to add the new module specifically to the planetary ISRU, but then found this.  Now I'm wondering whether I should submit my patch as a separate pull request (though this one is better), release it separately (seems silly for a single small `.cfg` file), or wait and hope for this change to be merged.

**Comment by toric55** [comment]
Really dont care. Nereta doesnt seem intrested in this, and im out e computer for now, but feel free to use this one for personal use, or even remind nereta about this. If you want your change in, not sure whether it would be better to put it here or kpbs. (I actually made it for kpbs and MKS, but it works for everything.)

**Comment by Wyzard256** [comment]
Yeah, my comment was directed more at Nertea, as sort of a ping saying hey, this patch has specific real-world benefits; it's not just an abstract hypothetical improvement.  I'm hoping to put it back onto the radar.

**Comment by ChrisAdderley** [comment]
I've merged the other patch for now. I prefer supporting specifics instead of all generality, I'll still continue to think about it.

**Pull request closed without merging**
