### PR TITLE
Add bulkheadProfiles to parts

### PR DESCRIPTION
**Pull request by lOmicronl**

### CODE REVIEW

**Comment by ChrisAdderley** [comment]
Can you resolve the conflict on your end?

**Comment by lOmicronl** [comment]
My GitHub skills only just barely extend to being able to fork a repository and request a pull into the original. I have absolutely no idea what is up in this case. I did the same thing to this file I that I did to all the others - namely, pressing CTRL+V and saving.

Can you just remove the offending file from the pull request? Can I do that? Do you have to reject the whole thing and let me make another request?

**Comment by ChrisAdderley** [comment]
No problem. You should be able to resolve the conflict by clicking on the resolve conflicts button directly below this message - it will bring up a web editor where it shows what the conflict is and it basically walks you through it. 

I can't do much to this PR because this is technically committing to your copy of the repo, not mine, so I don't have authorization.

**Comment by ChrisAdderley** [comment]
Alternately you could re-make this PR, but ensure you build it against `dev` this time (the conflict only appeared when I changed the base)

**Comment by lOmicronl** [comment]
I pushed some buttons that made some lights turn green. Does it work now? =P

Apparently the issue was that the changelog.txt file in your dev branch already had additional entries in it.

**Comment by ChrisAdderley** [comment]
Yep that was the problem. Nice work!

**Pull request merged**
